### ISSUE TITLE
Color stays white in effect mode?

### ISSUE THREAD

**Issue by CuriousxOctopus** [pobrn/ite8291r3-ctl#12]
Good day! I can change colors in monocolor, but the effect color stays white... I have even tried copying the example from the readme and got the same issue. any help would be appreciated.

**Comment by pobrn** [comment]
Please elaborate the commands you ran, what you expected to happen, and what happened instead. Post the output of `
ite8291r3-ctl query --devices` as well.

**Comment by CuriousxOctopus** [comment]
> Please elaborate the commands you ran, what you expected to happen, and what happened instead. Post the output of ` ite8291r3-ctl query --devices` as well.

I ran the code from the readme below

ite8291r3-ctl effect aurora -s 2 -c red -r

bus 1 addr 2 rev 0.03 product ce00:'ITE Device(8291)' manufacturer 048d:'ITE Tech. Inc.'

**Comment by pobrn** [comment]
Could you also run `ite8291r3-ctl query --fw-version`?

**Comment by CuriousxOctopus** [comment]
19.7.0.0

Thank you!

**Comment by CuriousxOctopus** [comment]
I used debug for :ite8291r3-ctl effect aurora -s 2 -c red -r

result:sending ctrl device: (8, 2, 14, 2, 25, 1, 1, 0)

Thanks!

**Comment by pobrn** [comment]
Can you run `ite8291r3-ctl palette --restore` and try again?

**Comment by CuriousxOctopus** [comment]
> Can you run `ite8291r3-ctl palette --restore` and try again?

It worked! Thank you friend!
