### ISSUE TITLE
Versioned releases?

### ISSUE THREAD

**Issue by abenson** [pobrn/ite8291r3-ctl#14]
I'd like to include this in [Void Linux](https://github.com/void-linux/void-packages/) but one of the quality requirements is [versioned releases](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements).  

Even a tag is enough, as long as it makes sense.

Thanks!

**Comment by pobrn** [comment]
Sorry for the late reply. The releases on PyPI are versioned, I'm assuming you want me to add tags in git?

**Comment by abenson** [comment]
PyPI will work, it just seems there hasn't been a release there in a long while either.
